

const data = [
  {
    id: 1,
first_name : 'yes',
last_name : 'bobo',
Sex : 'male',
primary_phone_number : '07',
secondary_phone_number: 'à-',
email_address: 'ss@ss',
way_contact: 'boo',
electro_or_not: 'yes',
birthday: '23/07/1999',
days_left: '23',
remark: '22',
last_reminder: '11',
VIP: '2',
created_at: '18/09/1999',
updated_at: '1',
deleted_at:'34',
asia_miles_membership: 'OUI',
actual_menu: 'NON',
type: 'BG',
woocommerce_customer_id: '22',
last_mail_sent: 'hier',
  },
  {
    id: 5,
first_name : 'yes',
last_name : 'bobo',
Sex : 'male',
primary_phone_number : '07',
secondary_phone_number: 'à-',
email_address: 'ss@ss',
way_contact: 'boo',
electro_or_not: 'yes',
birthday: '23/07/1999',
days_left: '23',
remark: '22',
last_reminder: '11',
VIP: '2',
created_at: '18/09/1999',
updated_at: '1',
deleted_at:'34',
asia_miles_membership: 'OUI',
actual_menu: 'NON',
type: 'BG',
woocommerce_customer_id: '22',
last_mail_sent: 'hier',
  },
  {
    id: 3,
first_name : 'yes',
last_name : 'bobo',
Sex : 'male',
primary_phone_number : '07',
secondary_phone_number: 'à-',
email_address: 'ss@ss',
way_contact: 'boo',
electro_or_not: 'yes',
birthday: '23/07/1999',
days_left: '23',
remark: '22',
last_reminder: '11',
VIP: '2',
created_at: '18/09/1999',
updated_at: '1',
deleted_at:'34',
asia_miles_membership: 'OUI',
actual_menu: 'NON',
type: 'BG',
woocommerce_customer_id: '22',
last_mail_sent: 'hier',
  },
  {
    id: 4,
first_name : 'yes',
last_name : 'bobo',
Sex : 'male',
primary_phone_number : '07',
secondary_phone_number: 'à-',
email_address: 'ss@ss',
way_contact: 'boo',
electro_or_not: 'yes',
birthday: '23/07/1999',
days_left: '23',
remark: '22',
last_reminder: '11',
VIP: '2',
created_at: '18/09/1999',
updated_at: '1',
deleted_at:'34',
asia_miles_membership: 'OUI',
actual_menu: 'NON',
type: 'BG',
woocommerce_customer_id: '22',
last_mail_sent: 'hier',
  }
]

export default data
